/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck -- duplicate contextual labels intentionally prefer the later translation.
import type { Locale } from "@/lib/i18n";

const ar: Record<string,string> = {
  "Appointment Booking":"منصة حجز المواعيد","E-Commerce Platform":"منصة التجارة الإلكترونية","Real Estate Marketplace":"سوق العقارات","A complete online appointment management platform for businesses that work with bookings and schedules.":"منصة متكاملة لإدارة المواعيد للشركات التي تعتمد على الحجوزات والجداول.","Transform a physical store into a complete online shopping business.":"حوّل متجرك الفعلي إلى مشروع تسوق إلكتروني متكامل.","A modern property platform for agencies, brokers and real estate businesses.":"منصة عقارية حديثة للوكالات والوسطاء وشركات العقارات.","An open marketplace connecting businesses with independent freelance couriers.":"سوق مفتوح يربط الشركات بمندوبي التوصيل المستقلين.",
  "Online booking":"الحجز عبر الإنترنت","Smart calendar":"تقويم ذكي","Employee schedules":"جداول الموظفين","Customer accounts":"حسابات العملاء","Notifications":"الإشعارات","Service management":"إدارة الخدمات","Business analytics":"تحليلات الأعمال","Multi-language support":"دعم متعدد اللغات","Product catalog":"كتالوج المنتجات","Search & categories":"البحث والتصنيفات","Cart & checkout":"السلة والدفع","Inventory":"إدارة المخزون","Discounts":"الخصومات","Reports":"التقارير","Property listings":"قوائم العقارات","Advanced filters":"فلاتر متقدمة","Maps":"الخرائط","Property galleries":"معارض الصور","Agent profiles":"ملفات الوكلاء","Favorites":"المفضلة","Contact requests":"طلبات التواصل","Delivery requests":"طلبات التوصيل","Courier marketplace":"سوق المندوبين","Courier offers":"عروض التوصيل","Live statuses":"الحالات المباشرة","Messaging":"المراسلة","Business dashboard":"لوحة الشركة","Courier dashboard":"لوحة المندوب",
  "Barbershops":"صالونات الحلاقة","Clinics":"العيادات","Dentists":"أطباء الأسنان","Beauty":"التجميل","Professional services":"الخدمات المهنية","Retail":"التجزئة","Electronics":"الإلكترونيات","Cosmetics":"مستحضرات التجميل","Furniture":"الأثاث","Specialty stores":"المتاجر المتخصصة","Agencies":"الوكالات","Brokers":"الوسطاء","Developers":"المطورون","Rental companies":"شركات التأجير","Restaurants":"المطاعم","Pharmacies":"الصيدليات","Shops":"المتاجر","Grocery":"البقالة","Delivery networks":"شبكات التوصيل",
  "Primary":"التنقل الرئيسي","Language":"اللغة","Toggle theme":"تبديل المظهر","Product interface previews":"معاينات واجهات المنتجات",
  "Booking":"حجز","Confirmed":"مؤكد","Available":"متاح","New arrivals":"وصل حديثًا","products":"منتجًا","Cart":"السلة","Orders":"الطلبات","Property map":"خريطة العقارات","Courier":"مندوب","min":"دقائق","Live status":"الحالة المباشرة",
  "Web Applications":"تطبيقات الويب","Mobile Apps":"تطبيقات الجوال","SaaS Platforms":"منصات SaaS","E-Commerce":"التجارة الإلكترونية","Booking Systems":"أنظمة الحجز","Automation":"الأتمتة","Admin Dashboards":"لوحات الإدارة","Cloud Deployment":"النشر السحابي",
  "READY-MADE SOLUTIONS":"حلول جاهزة","Built for real businesses.":"مصممة لأعمال حقيقية.","Choose a complete digital platform, try it free, customize it to your brand, and launch faster.":"اختر منصة رقمية متكاملة، جرّبها مجانًا، خصّصها لعلامتك التجارية، وانطلق بسرعة.",
  "SMART PRODUCT FINDER":"مستكشف المنتجات الذكي","What does your business need?":"ماذا يحتاج عملك؟","Service business":"أعمال الخدمات","Online store":"متجر إلكتروني","Real estate":"العقارات","Delivery / logistics":"التوصيل والخدمات اللوجستية","Recommended":"موصى به","Explore solution":"استكشف الحل",
  "A BETTER STARTING POINT":"نقطة بداية أفضل","Stop starting from zero.":"توقف عن البدء من الصفر.","A ready-made foundation can reduce discovery and implementation work while preserving room for your brand and workflow.":"تقلل المنصة الجاهزة أعمال التحليل والتنفيذ مع الحفاظ على مرونة علامتك التجارية وسير عملك.","Compare plans":"قارن الخطط","Custom from zero":"تطوير مخصص من الصفر","Long discovery and build":"تحليل وبناء طويلان","Our platform":"منصتنا","Already working":"جاهزة وتعمل","Your launch":"إطلاقك","Branding + configuration":"الهوية + الإعداد","Growth":"النمو","Subscription + support":"اشتراك + دعم",
  "Ready-made foundations":"أسس جاهزة","Fully customizable":"قابلة للتخصيص بالكامل","Multi-language":"متعددة اللغات","Mobile ready":"جاهزة للجوال","Scalable":"قابلة للتوسع","Secure":"آمنة","Production-focused systems designed around usability, flexibility, and long-term growth.":"أنظمة مهيأة للإنتاج ومصممة لسهولة الاستخدام والمرونة والنمو طويل الأمد.",
  "CUSTOM DEVELOPMENT":"تطوير مخصص","Need something different?":"هل تحتاج شيئًا مختلفًا؟","We build custom websites, mobile apps, SaaS systems, dashboards, APIs, automation, and internal tools.":"نبني مواقع وتطبيقات جوال وأنظمة SaaS ولوحات تحكم وواجهات API وأتمتة وأدوات داخلية مخصصة.","Build a custom application":"ابنِ تطبيقًا مخصصًا",
  "Calendar":"التقويم","Overview":"نظرة عامة","Listings":"العقارات","Live map":"الخريطة المباشرة","Analytics":"التحليلات","Activity":"النشاط",
  "Launch demo":"تشغيل العرض التجريبي","Continue to demo":"متابعة إلى العرض","Cancel":"إلغاء","This environment is provided for demonstration purposes. Information entered into the demo may be reset periodically. Do not enter sensitive personal or payment information.":"هذه البيئة مخصصة للعرض التجريبي. قد تتم إعادة ضبط المعلومات المدخلة دوريًا. لا تدخل معلومات شخصية أو معلومات دفع حساسة.","This demo URL has not been configured yet.":"لم يتم إعداد رابط العرض التجريبي بعد.",
  "DEMO CENTER":"مركز العروض التجريبية","Try Before You Buy.":"جرّب قبل أن تشتري.","Experience the customer flows, dashboards, and management tools in safe demonstration environments.":"استكشف تجربة العملاء ولوحات التحكم وأدوات الإدارة في بيئات تجريبية آمنة.",
  "SIMPLE, FLEXIBLE PLANS":"خطط بسيطة ومرنة","Choose your platform.":"اختر منصتك.","Start with the system your business needs. Upgrade as you grow.":"ابدأ بالنظام الذي يحتاجه عملك وطوّره مع نموك.","Monthly":"شهري","Yearly · save up to 17%":"سنوي · وفر حتى 17٪","Starter":"المبتدئة","Professional":"الاحترافية","Business":"الأعمال","Core platform":"المنصة الأساسية","1 location":"موقع واحد","Email support":"دعم عبر البريد","All core features":"جميع الميزات الأساسية","3 locations":"3 مواقع","Priority support":"دعم ذو أولوية","Advanced analytics":"تحليلات متقدمة","Expanded limits":"حدود موسعة","Custom workflows":"مسارات عمل مخصصة","Onboarding support":"دعم الإعداد","Advanced controls":"تحكم متقدم","year":"سنة","month":"شهر","Start now":"ابدأ الآن","Development preview prices. Production plans are loaded from the database and editable by an administrator.":"هذه أسعار معاينة للتطوير. تُحمّل خطط الإنتاج من قاعدة البيانات ويمكن للمسؤول تعديلها.",
  "View plans":"عرض الخطط","THE COMPLETE SYSTEM":"النظام المتكامل","Operate with confidence.":"أدر عملك بثقة.","A polished customer experience and practical management tools in one configurable platform.":"تجربة عملاء مصقولة وأدوات إدارة عملية في منصة واحدة قابلة للتهيئة.","MADE FOR":"مصممة لـ","Industries that fit.":"قطاعات تناسبها.","Try it before you decide.":"جرّبها قبل أن تقرر.","Explore the demo, then choose the plan and customization level that suits your business.":"استكشف العرض ثم اختر الخطة ومستوى التخصيص المناسبين لعملك.","Ask a question":"اطرح سؤالًا",
  "LET'S BUILD":"لنبدأ البناء","Tell us what you need.":"أخبرنا بما تحتاجه.","Ready-made platform or completely custom system—we’ll help you find the right starting point.":"منصة جاهزة أو نظام مخصص بالكامل—سنساعدك في اختيار نقطة البداية المناسبة.","Start a conversation.":"ابدأ محادثة.","Name":"الاسم","Business name":"اسم الشركة","Email":"البريد الإلكتروني","Phone":"الهاتف","Interested product":"المنتج المطلوب","Choose a product":"اختر منتجًا","Preferred contact method":"طريقة التواصل المفضلة","WhatsApp":"واتساب","Message":"الرسالة","I agree to be contacted about this request.":"أوافق على التواصل معي بخصوص هذا الطلب.","Request demo":"اطلب عرضًا تجريبيًا","Request consultation":"اطلب استشارة",
  "GUIDED DEMO":"عرض تجريبي موجه","See it in your workflow.":"شاهده ضمن سير عملك.","REQUEST RECEIVED":"تم استلام الطلب","Thank you.":"شكرًا لك.","We’ve stored your request and will follow up using your preferred contact details.":"تم حفظ طلبك وسنتواصل معك عبر وسيلة الاتصال المفضلة.","Back home":"العودة للرئيسية",
  "OUR MISSION":"مهمتنا","Software that moves business forward.":"برمجيات تدفع الأعمال إلى الأمام.","creates powerful digital platforms that help businesses operate, sell, and grow online.":"تنشئ منصات رقمية قوية تساعد الشركات على الإدارة والبيع والنمو عبر الإنترنت.","We don’t just build websites. We build complete digital business systems.":"نحن لا نبني مواقع فقط، بل نبني أنظمة أعمال رقمية متكاملة.","Our ready-made platforms combine a proven foundation with the flexibility to reflect each client’s brand and workflow. When the right foundation doesn’t exist, we design a custom one.":"تجمع منصاتنا الجاهزة بين أساس موثوق ومرونة تعكس علامة كل عميل وسير عمله. وعندما لا يوجد الأساس المناسب، نصمم نظامًا مخصصًا.","We don’t publish invented company milestones, team sizes, or customer results. Case studies and testimonials are only published after genuine client approval.":"لا ننشر إنجازات أو أعداد فرق أو نتائج عملاء مختلقة. تُنشر دراسات الحالة والشهادات بعد موافقة العملاء الحقيقيين فقط.",
  "LEGAL DRAFT":"مسودة قانونية","Privacy Policy":"سياسة الخصوصية","Terms of Service":"شروط الخدمة","This placeholder must be reviewed and replaced by qualified counsel before production launch.":"يجب مراجعة هذا النص واستبداله بواسطة مستشار قانوني مؤهل قبل الإطلاق.","CASE STUDIES":"دراسات الحالة","Real work. Verified results.":"عمل حقيقي ونتائج موثقة.","No case studies are published yet. The admin-backed model is ready for genuine client stories.":"لا توجد دراسات حالة منشورة بعد. النظام الإداري جاهز لإضافة قصص عملاء حقيقية.",
  "SECURE CHECKOUT":"دفع آمن","Confirm your plan.":"أكد خطتك.","DEVELOPMENT PAYMENT MODE":"وضع دفع التطوير","Product":"المنتج","Plan":"الخطة","Billing":"الفوترة","Continue to payment":"المتابعة إلى الدفع","Payment status is confirmed by a verified provider webhook—not by this page.":"تُؤكد حالة الدفع عبر إشعار موثّق من مزود الدفع، وليس عبر هذه الصفحة.","Simulate checkout":"محاكاة الدفع","No real payment will be taken. This flow exists only for local testing.":"لن يتم تحصيل أي مبلغ حقيقي. هذا المسار للاختبار المحلي فقط.","Simulate successful subscription":"محاكاة اشتراك ناجح","Simulate failed payment":"محاكاة دفع فاشل","WELCOME":"مرحبًا","Your subscription is active.":"اشتراكك نشط.","Next: complete your business information, share your branding, choose a domain, and submit any customization requirements.":"الخطوة التالية: أكمل معلومات عملك وهوية علامتك واختر النطاق وأرسل متطلبات التخصيص.","Business information":"معلومات الشركة","Logo and colors":"الشعار والألوان","Preferred domain":"النطاق المفضل","Customization request":"طلب تخصيص","Start setup":"ابدأ الإعداد",
  "Page not found.":"الصفحة غير موجودة.","Return home":"العودة للرئيسية","SOMETHING WENT WRONG":"حدث خطأ ما","We couldn’t load this page.":"تعذر تحميل هذه الصفحة.","The error was logged without exposing private details.":"تم تسجيل الخطأ دون كشف بيانات خاصة.","Try again":"حاول مجددًا","Access denied.":"تم رفض الوصول.","You don’t have permission to access this area.":"ليس لديك إذن للوصول إلى هذه المنطقة.",
  "CLIENT PORTAL":"بوابة العملاء","ADMIN CONTROL":"لوحة الإدارة","My Products":"منتجاتي","Subscriptions":"الاشتراكات","Requests":"الطلبات","Support":"الدعم","Profile":"الملف الشخصي","Security":"الأمان","Clients":"العملاء","Products & Plans":"المنتجات والخطط","Content":"المحتوى","Leads":"العملاء المحتملون",
  "OVERVIEW":"نظرة عامة","Good to see you,":"سعدنا برؤيتك،","Active products":"المنتجات النشطة","Monthly cost":"التكلفة الشهرية","Support requests":"طلبات الدعم","Next billing":"الفوترة القادمة","Your products":"منتجاتك","Manage":"إدارة","You haven’t added a platform yet.":"لم تضف منصة بعد.","Explore the solutions and choose the right foundation.":"استكشف الحلول واختر الأساس المناسب.","Explore solutions":"استكشف الحلول","BILLING":"الفوترة","Subscriptions & invoices":"الاشتراكات والفواتير","renews":"يتجدد","Change plan":"تغيير الخطة","Cancel at renewal":"الإلغاء عند التجديد","No billing history yet.":"لا يوجد سجل فوترة بعد.","SUPPORT":"الدعم","How can we help?":"كيف يمكننا مساعدتك؟","General":"عام","Category":"الفئة","Technical issue":"مشكلة تقنية","Customization":"التخصيص","Domain":"النطاق","Feature request":"طلب ميزة","Other":"أخرى","Subject":"الموضوع","Create ticket":"إنشاء تذكرة","No support tickets.":"لا توجد تذاكر دعم.","MY PRODUCTS":"منتجاتي","Your software portfolio":"مجموعة برمجياتك","Setup:":"الإعداد:","Complete":"مكتمل","Required":"مطلوب","Provisioning:":"التجهيز:","No products yet.":"لا توجد منتجات بعد.","CUSTOMIZATION":"التخصيص","Your requests":"طلباتك","No customization requests yet.":"لا توجد طلبات تخصيص بعد.","PROFILE":"الملف الشخصي","Account information":"معلومات الحساب","Full name":"الاسم الكامل","Preferred language":"اللغة المفضلة","English":"الإنجليزية","Arabic":"العربية","Hebrew":"العبرية","Save changes":"حفظ التغييرات","SECURITY":"الأمان","Password & sessions":"كلمة المرور والجلسات","Change password":"تغيير كلمة المرور","Use a unique password of at least 10 characters.":"استخدم كلمة مرور فريدة من 10 أحرف على الأقل.","Update password":"تحديث كلمة المرور","Active sessions":"الجلسات النشطة","Current browser · active now":"المتصفح الحالي · نشط الآن",
  "ADMIN OVERVIEW":"نظرة عامة للإدارة","Business at a glance.":"نظرة سريعة على الأعمال.","Total clients":"إجمالي العملاء","Active subscriptions":"الاشتراكات النشطة","Monthly recurring":"الإيراد الشهري المتكرر","Annual run rate":"المعدل السنوي","New this month":"الجدد هذا الشهر","Cancellations":"الإلغاءات","Open tickets":"التذاكر المفتوحة","Product distribution":"توزيع المنتجات","CLIENTS":"العملاء","Client management":"إدارة العملاء","Business":"الشركة","Products":"المنتجات","Status":"الحالة","Registered":"تاريخ التسجيل","CATALOG & PRICING":"الكتالوج والأسعار","Products and plans":"المنتجات والخطط","Add product":"إضافة منتج","plans":"خطط","Edit":"تعديل","Demo:":"العرض:","Not configured":"غير مُعد","ORDERS & PROVISIONING":"الطلبات والتجهيز","Update":"تحديث","Support queue":"قائمة الدعم","messages":"رسائل","Open ticket":"فتح التذكرة","Review":"مراجعة","CONTENT":"المحتوى","Site configuration":"إعدادات الموقع","Manage headlines, FAQs, company details, statistics, and social links without changing components.":"أدر العناوين والأسئلة الشائعة وبيانات الشركة والإحصاءات والروابط الاجتماعية دون تعديل المكونات.","Add content block":"إضافة كتلة محتوى","LEADS":"العملاء المحتملون","New business requests":"طلبات أعمال جديدة"
};

const he: Record<string,string> = {
  "Appointment Booking":"מערכת זימון תורים","E-Commerce Platform":"פלטפורמת מסחר אלקטרוני","Real Estate Marketplace":"זירת נדל״ן","A complete online appointment management platform for businesses that work with bookings and schedules.":"מערכת מלאה לניהול תורים לעסקים העובדים עם הזמנות ולוחות זמנים.","Transform a physical store into a complete online shopping business.":"הפכו חנות פיזית לעסק קניות מקוון מלא.","A modern property platform for agencies, brokers and real estate businesses.":"פלטפורמת נכסים מודרנית לסוכנויות, מתווכים וחברות נדל״ן.","An open marketplace connecting businesses with independent freelance couriers.":"זירה פתוחה המחברת עסקים עם שליחים עצמאיים.",
  "Online booking":"הזמנה מקוונת","Smart calendar":"יומן חכם","Employee schedules":"משמרות עובדים","Customer accounts":"חשבונות לקוחות","Notifications":"התראות","Service management":"ניהול שירותים","Business analytics":"ניתוח עסקי","Multi-language support":"תמיכה בריבוי שפות","Product catalog":"קטלוג מוצרים","Search & categories":"חיפוש וקטגוריות","Cart & checkout":"עגלה ותשלום","Inventory":"ניהול מלאי","Discounts":"הנחות","Reports":"דוחות","Property listings":"רשימות נכסים","Advanced filters":"סינון מתקדם","Maps":"מפות","Property galleries":"גלריות נכסים","Agent profiles":"פרופילי סוכנים","Favorites":"מועדפים","Contact requests":"בקשות קשר","Delivery requests":"בקשות משלוח","Courier marketplace":"זירת שליחים","Courier offers":"הצעות שליחים","Live statuses":"מצבים בזמן אמת","Messaging":"הודעות","Business dashboard":"לוח עסקי","Courier dashboard":"לוח שליח",
  "Barbershops":"מספרות","Clinics":"מרפאות","Dentists":"רופאי שיניים","Beauty":"יופי","Professional services":"שירותים מקצועיים","Retail":"קמעונאות","Electronics":"אלקטרוניקה","Cosmetics":"קוסמטיקה","Furniture":"ריהוט","Specialty stores":"חנויות מתמחות","Agencies":"סוכנויות","Brokers":"מתווכים","Developers":"יזמים","Rental companies":"חברות השכרה","Restaurants":"מסעדות","Pharmacies":"בתי מרקחת","Shops":"חנויות","Grocery":"מכולת","Delivery networks":"רשתות משלוחים",
  "Primary":"ניווט ראשי","Language":"שפה","Toggle theme":"החלפת ערכת נושא","Product interface previews":"תצוגות מקדימות של המוצרים",
  "Booking":"הזמנה","Confirmed":"מאושר","Available":"זמין","New arrivals":"חדש באתר","products":"מוצרים","Cart":"עגלה","Orders":"הזמנות","Property map":"מפת נכסים","Courier":"שליח","min":"דקות","Live status":"מצב בזמן אמת",
  "Web Applications":"יישומי ווב","Mobile Apps":"אפליקציות מובייל","SaaS Platforms":"פלטפורמות SaaS","E-Commerce":"מסחר אלקטרוני","Booking Systems":"מערכות תורים","Automation":"אוטומציה","Admin Dashboards":"לוחות ניהול","Cloud Deployment":"פריסה בענן",
  "READY-MADE SOLUTIONS":"פתרונות מוכנים","Built for real businesses.":"נבנה לעסקים אמיתיים.","Choose a complete digital platform, try it free, customize it to your brand, and launch faster.":"בחרו פלטפורמה דיגיטלית מלאה, נסו בחינם, התאימו למותג והשיקו מהר יותר.",
  "SMART PRODUCT FINDER":"מאתר המוצרים החכם","What does your business need?":"מה העסק שלכם צריך?","Service business":"עסק שירותים","Online store":"חנות מקוונת","Real estate":"נדל״ן","Delivery / logistics":"משלוחים ולוגיסטיקה","Recommended":"מומלץ","Explore solution":"לפתרון",
  "A BETTER STARTING POINT":"נקודת פתיחה טובה יותר","Stop starting from zero.":"הפסיקו להתחיל מאפס.","A ready-made foundation can reduce discovery and implementation work while preserving room for your brand and workflow.":"בסיס מוכן מצמצם אפיון והטמעה ועדיין משאיר מקום למותג ולתהליך העבודה שלכם.","Compare plans":"השוואת מסלולים","Custom from zero":"פיתוח מאפס","Long discovery and build":"אפיון ובנייה ארוכים","Our platform":"הפלטפורמה שלנו","Already working":"כבר עובדת","Your launch":"ההשקה שלכם","Branding + configuration":"מיתוג + הגדרה","Growth":"צמיחה","Subscription + support":"מנוי + תמיכה",
  "Ready-made foundations":"בסיסים מוכנים","Fully customizable":"התאמה מלאה","Multi-language":"ריבוי שפות","Mobile ready":"מוכן למובייל","Scalable":"ניתן להרחבה","Secure":"מאובטח","Production-focused systems designed around usability, flexibility, and long-term growth.":"מערכות מוכנות לייצור המתוכננות לשימושיות, גמישות וצמיחה לטווח ארוך.",
  "CUSTOM DEVELOPMENT":"פיתוח מותאם","Need something different?":"צריכים משהו אחר?","We build custom websites, mobile apps, SaaS systems, dashboards, APIs, automation, and internal tools.":"אנחנו בונים אתרים, אפליקציות, מערכות SaaS, לוחות בקרה, ממשקי API, אוטומציה וכלים פנימיים בהתאמה אישית.","Build a custom application":"בניית יישום מותאם",
  "Calendar":"יומן","Overview":"סקירה","Listings":"נכסים","Live map":"מפה חיה","Analytics":"ניתוח נתונים","Activity":"פעילות",
  "Launch demo":"פתיחת הדגמה","Continue to demo":"המשך להדגמה","Cancel":"ביטול","This environment is provided for demonstration purposes. Information entered into the demo may be reset periodically. Do not enter sensitive personal or payment information.":"סביבה זו מיועדת להדגמה. מידע שיוזן עשוי להתאפס מעת לעת. אין להזין מידע אישי או פרטי תשלום רגישים.","This demo URL has not been configured yet.":"כתובת ההדגמה עדיין לא הוגדרה.",
  "DEMO CENTER":"מרכז הדגמות","Try Before You Buy.":"נסו לפני הרכישה.","Experience the customer flows, dashboards, and management tools in safe demonstration environments.":"התנסו בתהליכי הלקוחות, לוחות הבקרה וכלי הניהול בסביבות הדגמה בטוחות.",
  "SIMPLE, FLEXIBLE PLANS":"מסלולים פשוטים וגמישים","Choose your platform.":"בחרו את הפלטפורמה.","Start with the system your business needs. Upgrade as you grow.":"התחילו במערכת שהעסק צריך ושדרגו עם הצמיחה.","Monthly":"חודשי","Yearly · save up to 17%":"שנתי · חיסכון של עד 17%","Starter":"התחלתי","Professional":"מקצועי","Business":"עסקי","Core platform":"פלטפורמת ליבה","1 location":"מיקום אחד","Email support":"תמיכה בדוא״ל","All core features":"כל תכונות הליבה","3 locations":"3 מיקומים","Priority support":"תמיכה בעדיפות","Advanced analytics":"ניתוח מתקדם","Expanded limits":"מגבלות מורחבות","Custom workflows":"תהליכים מותאמים","Onboarding support":"תמיכת הקמה","Advanced controls":"בקרות מתקדמות","year":"שנה","month":"חודש","Start now":"מתחילים עכשיו","Development preview prices. Production plans are loaded from the database and editable by an administrator.":"אלו מחירי תצוגת פיתוח. מסלולי הייצור נטענים ממסד הנתונים וניתנים לעריכת מנהל.",
  "View plans":"הצגת מסלולים","THE COMPLETE SYSTEM":"המערכת המלאה","Operate with confidence.":"נהלו בביטחון.","A polished customer experience and practical management tools in one configurable platform.":"חוויית לקוח מלוטשת וכלי ניהול מעשיים בפלטפורמה אחת הניתנת להגדרה.","MADE FOR":"מתאים עבור","Industries that fit.":"ענפים מתאימים.","Try it before you decide.":"נסו לפני שמחליטים.","Explore the demo, then choose the plan and customization level that suits your business.":"הכירו את ההדגמה ואז בחרו מסלול ורמת התאמה המתאימים לעסק.","Ask a question":"שאלו שאלה",
  "LET'S BUILD":"בואו נבנה","Tell us what you need.":"ספרו לנו מה אתם צריכים.","Ready-made platform or completely custom system—we’ll help you find the right starting point.":"פלטפורמה מוכנה או מערכת מותאמת לחלוטין—נעזור למצוא את נקודת הפתיחה הנכונה.","Start a conversation.":"בואו נדבר.","Name":"שם","Business name":"שם העסק","Email":"דוא״ל","Phone":"טלפון","Interested product":"מוצר מבוקש","Choose a product":"בחירת מוצר","Preferred contact method":"דרך התקשרות מועדפת","WhatsApp":"וואטסאפ","Message":"הודעה","I agree to be contacted about this request.":"אני מסכים/ה שייצרו איתי קשר בנוגע לבקשה.","Request demo":"בקשת הדגמה","Request consultation":"בקשת ייעוץ",
  "GUIDED DEMO":"הדגמה מודרכת","See it in your workflow.":"ראו זאת בתהליך העבודה שלכם.","REQUEST RECEIVED":"הבקשה התקבלה","Thank you.":"תודה.","We’ve stored your request and will follow up using your preferred contact details.":"הבקשה נשמרה ונחזור אליכם בדרך ההתקשרות המועדפת.","Back home":"חזרה לדף הבית",
  "OUR MISSION":"המשימה שלנו","Software that moves business forward.":"תוכנה שמקדמת עסקים.","creates powerful digital platforms that help businesses operate, sell, and grow online.":"יוצרת פלטפורמות דיגיטליות חזקות המסייעות לעסקים לנהל, למכור ולצמוח ברשת.","We don’t just build websites. We build complete digital business systems.":"אנחנו לא רק בונים אתרים. אנחנו בונים מערכות עסקיות דיגיטליות מלאות.","Our ready-made platforms combine a proven foundation with the flexibility to reflect each client’s brand and workflow. When the right foundation doesn’t exist, we design a custom one.":"הפלטפורמות המוכנות שלנו משלבות בסיס מוכח עם גמישות למותג ולתהליך של כל לקוח. כשאין בסיס מתאים, אנחנו מתכננים פתרון מותאם.","We don’t publish invented company milestones, team sizes, or customer results. Case studies and testimonials are only published after genuine client approval.":"איננו מפרסמים אבני דרך, גודל צוות או תוצאות לקוחות מומצאות. מקרי בוחן והמלצות מתפרסמים רק לאחר אישור לקוח אמיתי.",
  "LEGAL DRAFT":"טיוטה משפטית","Privacy Policy":"מדיניות פרטיות","Terms of Service":"תנאי שירות","This placeholder must be reviewed and replaced by qualified counsel before production launch.":"יש לבדוק ולהחליף טקסט זה באמצעות יועץ משפטי מוסמך לפני ההשקה.","CASE STUDIES":"מקרי בוחן","Real work. Verified results.":"עבודה אמיתית. תוצאות מאומתות.","No case studies are published yet. The admin-backed model is ready for genuine client stories.":"עדיין לא פורסמו מקרי בוחן. מודל הניהול מוכן לסיפורי לקוחות אמיתיים.",
  "SECURE CHECKOUT":"תשלום מאובטח","Confirm your plan.":"אשרו את המסלול.","DEVELOPMENT PAYMENT MODE":"מצב תשלום לפיתוח","Product":"מוצר","Plan":"מסלול","Billing":"חיוב","Continue to payment":"המשך לתשלום","Payment status is confirmed by a verified provider webhook—not by this page.":"מצב התשלום מאושר באמצעות התראה מאומתת של הספק, ולא בדף זה.","Simulate checkout":"הדמיית תשלום","No real payment will be taken. This flow exists only for local testing.":"לא ייגבה תשלום אמיתי. תהליך זה מיועד לבדיקה מקומית בלבד.","Simulate successful subscription":"הדמיית מנוי מוצלח","Simulate failed payment":"הדמיית תשלום שנכשל","WELCOME":"ברוכים הבאים","Your subscription is active.":"המנוי פעיל.","Next: complete your business information, share your branding, choose a domain, and submit any customization requirements.":"השלב הבא: השלימו פרטי עסק, מיתוג, דומיין ודרישות התאמה.","Business information":"פרטי העסק","Logo and colors":"לוגו וצבעים","Preferred domain":"דומיין מועדף","Customization request":"בקשת התאמה","Start setup":"התחלת ההקמה",
  "Page not found.":"הדף לא נמצא.","Return home":"חזרה לדף הבית","SOMETHING WENT WRONG":"משהו השתבש","We couldn’t load this page.":"לא הצלחנו לטעון את הדף.","The error was logged without exposing private details.":"השגיאה נרשמה ללא חשיפת פרטים אישיים.","Try again":"נסו שוב","Access denied.":"הגישה נדחתה.","You don’t have permission to access this area.":"אין לכם הרשאה לגשת לאזור זה.",
  "CLIENT PORTAL":"פורטל לקוחות","ADMIN CONTROL":"בקרת מנהל","My Products":"המוצרים שלי","Subscriptions":"מנויים","Requests":"בקשות","Support":"תמיכה","Profile":"פרופיל","Security":"אבטחה","Clients":"לקוחות","Products & Plans":"מוצרים ומסלולים","Content":"תוכן","Leads":"פניות",
  "OVERVIEW":"סקירה","Good to see you,":"טוב לראות אותך,","Active products":"מוצרים פעילים","Monthly cost":"עלות חודשית","Support requests":"בקשות תמיכה","Next billing":"החיוב הבא","Your products":"המוצרים שלכם","Manage":"ניהול","You haven’t added a platform yet.":"עדיין לא הוספתם פלטפורמה.","Explore the solutions and choose the right foundation.":"גלו את הפתרונות ובחרו את הבסיס המתאים.","Explore solutions":"לצפייה בפתרונות","BILLING":"חיוב","Subscriptions & invoices":"מנויים וחשבוניות","renews":"מתחדש","Change plan":"שינוי מסלול","Cancel at renewal":"ביטול בחידוש","No billing history yet.":"אין עדיין היסטוריית חיוב.","SUPPORT":"תמיכה","How can we help?":"איך אפשר לעזור?","General":"כללי","Category":"קטגוריה","Technical issue":"בעיה טכנית","Customization":"התאמה","Domain":"דומיין","Feature request":"בקשת תכונה","Other":"אחר","Subject":"נושא","Create ticket":"פתיחת פנייה","No support tickets.":"אין פניות תמיכה.","MY PRODUCTS":"המוצרים שלי","Your software portfolio":"תיק התוכנה שלכם","Setup:":"הקמה:","Complete":"הושלם","Required":"נדרש","Provisioning:":"אספקה:","No products yet.":"אין עדיין מוצרים.","CUSTOMIZATION":"התאמה","Your requests":"הבקשות שלכם","No customization requests yet.":"אין עדיין בקשות התאמה.","PROFILE":"פרופיל","Account information":"פרטי החשבון","Full name":"שם מלא","Preferred language":"שפה מועדפת","English":"אנגלית","Arabic":"ערבית","Hebrew":"עברית","Save changes":"שמירת שינויים","SECURITY":"אבטחה","Password & sessions":"סיסמה והפעלות","Change password":"שינוי סיסמה","Use a unique password of at least 10 characters.":"השתמשו בסיסמה ייחודית בת 10 תווים לפחות.","Update password":"עדכון סיסמה","Active sessions":"הפעלות פעילות","Current browser · active now":"הדפדפן הנוכחי · פעיל עכשיו",
  "ADMIN OVERVIEW":"סקירת מנהל","Business at a glance.":"העסק במבט מהיר.","Total clients":"סך הלקוחות","Active subscriptions":"מנויים פעילים","Monthly recurring":"הכנסה חודשית חוזרת","Annual run rate":"קצב שנתי","New this month":"חדשים החודש","Cancellations":"ביטולים","Open tickets":"פניות פתוחות","Product distribution":"התפלגות מוצרים","CLIENTS":"לקוחות","Client management":"ניהול לקוחות","Business":"עסק","Products":"מוצרים","Status":"מצב","Registered":"תאריך הרשמה","CATALOG & PRICING":"קטלוג ומחירים","Products and plans":"מוצרים ומסלולים","Add product":"הוספת מוצר","plans":"מסלולים","Edit":"עריכה","Demo:":"הדגמה:","Not configured":"לא הוגדר","ORDERS & PROVISIONING":"הזמנות ואספקה","Update":"עדכון","Support queue":"תור התמיכה","messages":"הודעות","Open ticket":"פתיחת פנייה","Review":"בדיקה","CONTENT":"תוכן","Site configuration":"הגדרות האתר","Manage headlines, FAQs, company details, statistics, and social links without changing components.":"נהלו כותרות, שאלות נפוצות, פרטי חברה, נתונים וקישורים חברתיים ללא שינוי רכיבים.","Add content block":"הוספת בלוק תוכן","LEADS":"פניות","New business requests":"בקשות עסקיות חדשות"
};

export const uiPhrases: Record<Exclude<Locale,"en">,Record<string,string>>={ar,he};
