import crypto from "node:crypto";
import { db } from "./db";
import type { Prisma } from "../../generated/prisma/client";
export type CheckoutInput={userId:string;productId:string;planId:string;interval:"MONTHLY"|"YEARLY";successUrl:string;cancelUrl:string};
export interface PaymentProvider{capabilities:{changePlan:boolean;cancel:boolean;billingPortal:boolean};createCustomer(input:{email:string;name:string}):Promise<{id:string}>;createCheckoutSession(input:CheckoutInput):Promise<{id:string;url:string}>;cancelSubscription(id:string):Promise<void>;changePlan(id:string,planId:string):Promise<void>;getInvoices(customerId:string):Promise<unknown[]>;verifyWebhook(raw:string,signature:string):Promise<ProviderEvent>}
export type ProviderEvent={id:string;type:"subscription.created"|"payment.succeeded"|"payment.failed"|"subscription.renewed"|"subscription.cancelled"|"subscription.expired"|"refund.created";subscriptionId:string;occurredAt:Date;payload:Prisma.InputJsonValue};
class MockPaymentProvider implements PaymentProvider{capabilities={changePlan:true,cancel:true,billingPortal:false};async createCustomer(){return{id:`mock_customer_${crypto.randomUUID()}`}}async createCheckoutSession(input:CheckoutInput){if(process.env.NODE_ENV==="production")throw new Error("Mock billing is forbidden in production");return{id:`mock_checkout_${crypto.randomUUID()}`,url:`${process.env.APP_URL}/en/checkout/mock?plan=${input.planId}&product=${input.productId}&interval=${input.interval}`}}async cancelSubscription(){}async changePlan(){}async getInvoices(){return[]}async verifyWebhook(raw:string,signature:string){const expected=crypto.createHmac("sha256",process.env.PAYMENT_WEBHOOK_SECRET||"").update(raw).digest("hex");if(!signature||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(signature)))throw new Error("Invalid webhook signature");return JSON.parse(raw) as ProviderEvent}}
export function paymentProvider():PaymentProvider{const provider=process.env.PAYMENT_PROVIDER||"mock";if(process.env.NODE_ENV==="production"&&provider==="mock")throw new Error("Production refuses PAYMENT_PROVIDER=mock");if(provider==="mock")return new MockPaymentProvider();throw new Error(`Payment provider '${provider}' has not been configured`)}
export async function processPaymentEvent(provider:string,event:ProviderEvent){return db.$transaction(async tx=>{const prior=await tx.paymentEvent.findUnique({where:{providerEventId:event.id}});if(prior)return prior;const stored=await tx.paymentEvent.create({data:{provider,providerEventId:event.id,type:event.type,payload:event.payload}});const subscription=await tx.subscription.findUnique({where:{providerSubscriptionId:event.subscriptionId}});if(subscription){const status=event.type==="payment.failed"?"PAST_DUE":event.type==="subscription.cancelled"?"CANCELLED":event.type==="subscription.expired"?"EXPIRED":"ACTIVE";await tx.subscription.update({where:{id:subscription.id},data:{status}});await tx.entitlement.upsert({where:{userId_productId_key:{userId:subscription.userId,productId:subscription.productId,key:"product_access"}},create:{userId:subscription.userId,productId:subscription.productId,subscriptionId:subscription.id,active:status==="ACTIVE"},update:{active:status==="ACTIVE",subscriptionId:subscription.id}});await tx.notification.create({data:{userId:subscription.userId,type:event.type,title:event.type.replaceAll("."," ")}})}return tx.paymentEvent.update({where:{id:stored.id},data:{processedAt:new Date()}})})}
