import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client";
import { hashPassword } from "better-auth/crypto";
if(process.env.NODE_ENV==="production")throw new Error("Development seed is disabled in production");
if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required");
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const products=[
 {slug:"appointments",name:"Appointment Booking",shortDescription:"Booking, calendars, staff, customers and analytics.",description:"A complete online appointment management platform.",order:1,url:process.env.NEXT_PUBLIC_APPOINTMENTS_DEMO_URL},
 {slug:"ecommerce",name:"E-Commerce Platform",shortDescription:"Catalog, checkout, orders and inventory.",description:"A complete online shopping platform.",order:2,url:process.env.NEXT_PUBLIC_ECOMMERCE_DEMO_URL},
 {slug:"real-estate",name:"Real Estate Marketplace",shortDescription:"Listings, maps, agents and inquiries.",description:"A modern property marketplace.",order:3,url:process.env.NEXT_PUBLIC_REAL_ESTATE_DEMO_URL},
];
async function user(email:string,name:string,role:"CLIENT"|"ADMIN",password:string){const passwordHash=await hashPassword(password);return db.user.upsert({where:{email},update:{role,emailVerified:true},create:{email,name,role,emailVerified:true,accounts:{create:{accountId:email,providerId:"credential",password:passwordHash}}}})}
async function main(){
 await db.product.updateMany({where:{slug:"opendelivery"},data:{status:"ARCHIVED",featured:false}});
 const seeded=[];for(const p of products){const product=await db.product.upsert({where:{slug:p.slug},update:{},create:{name:p.name,slug:p.slug,shortDescription:p.shortDescription,description:p.description,status:"ACTIVE",featured:true,displayOrder:p.order}});for(const [index,plan] of ["Starter","Professional","Business"].entries()){await db.productPlan.upsert({where:{productId_slug:{productId:product.id,slug:plan.toLowerCase()}},update:{},create:{productId:product.id,name:plan,slug:plan.toLowerCase(),monthlyPrice:[14900,29900,59900][index],annualPrice:[149000,299000,599000][index],currency:"ILS",features:["Core platform","Responsive experience","Support"],limits:{locations:index+1},trialDays:index===0?7:0,displayOrder:index}})}if(p.url)await db.demoConfiguration.upsert({where:{id:`demo-${p.slug}`},update:{url:p.url},create:{id:`demo-${p.slug}`,productId:product.id,name:`${p.name} Demo`,url:p.url}});seeded.push(product)}
 const adminPassword=process.env.DEV_ADMIN_PASSWORD||"ChangeMe123!";const admin=await user(process.env.DEV_ADMIN_EMAIL||"admin@example.test","Development Admin","ADMIN",adminPassword);const client=await user("client@example.test","Development Client","CLIENT","ChangeMe123!");await db.businessProfile.upsert({where:{userId:client.id},update:{},create:{userId:client.id,businessName:"Sample Business (Development)"}});const plan=await db.productPlan.findFirstOrThrow({where:{productId:seeded[0].id,slug:"professional"}});const appointmentAccessUrl=process.env.DEV_APPOINTMENTS_ACCESS_URL||"http://localhost:5173/?tenant=elite-barber";const subscription=await db.subscription.upsert({where:{providerSubscriptionId:"mock_seed_subscription"},update:{externalTenantId:"elite-barber",externalAccessUrl:appointmentAccessUrl,provisioningStatus:"ACTIVE",provisionedAt:new Date()},create:{userId:client.id,productId:seeded[0].id,planId:plan.id,provider:"mock",providerCustomerId:"mock_seed_customer",providerSubscriptionId:"mock_seed_subscription",billingInterval:"MONTHLY",status:"ACTIVE",provisioningStatus:"ACTIVE",externalTenantId:"elite-barber",externalAccessUrl:appointmentAccessUrl,provisionedAt:new Date(),currentPeriodStart:new Date(),currentPeriodEnd:new Date(Date.now()+30*86400000),entitlements:{create:{userId:client.id,productId:seeded[0].id}}}});await db.supportTicket.create({data:{userId:client.id,productId:seeded[0].id,category:"CUSTOMIZATION",subject:"Sample development support ticket",messages:{create:{authorId:client.id,body:"This is clearly labeled development seed data."}}}});console.log(`Development data created. Admin: ${admin.email}; Client: client@example.test; Password: ChangeMe123!; Subscription: ${subscription.id}`)
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>db.$disconnect());
