"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/lib/db";
import { requireAdmin,requireUser } from "@/lib/authorization";
import { provisioningProvider } from "@/lib/provisioning";

const leadSchema=z.object({type:z.enum(["CONTACT","DEMO","CUSTOM_DEVELOPMENT"]),name:z.string().min(2).max(100),businessName:z.string().max(120).optional(),email:z.email(),phone:z.string().max(40).optional(),productSlug:z.string().max(80).optional(),preferredContact:z.string().max(30).optional(),message:z.string().min(10).max(4000),consent:z.literal("on").transform(()=>true)});
export async function submitLead(form:FormData){const parsed=leadSchema.safeParse(Object.fromEntries(form));if(!parsed.success)throw new Error("Please check the form fields");await db.lead.create({data:parsed.data});redirect("/en/contact/success")}
const ticketSchema=z.object({productId:z.string().optional(),category:z.enum(["TECHNICAL","BILLING","CUSTOMIZATION","DOMAIN","FEATURE_REQUEST","OTHER"]),subject:z.string().min(4).max(160),message:z.string().min(10).max(5000)});
export async function createTicket(form:FormData){const session=await requireUser();const input=ticketSchema.parse(Object.fromEntries(form));await db.supportTicket.create({data:{userId:session.user.id,productId:input.productId||null,category:input.category,subject:input.subject,messages:{create:{authorId:session.user.id,body:input.message}}}});revalidatePath("/en/dashboard/support")}
export async function updateProvisioning(form:FormData){const session=await requireAdmin();const id=z.string().parse(form.get("subscriptionId"));const status=z.enum(["PURCHASED","SETUP_REQUIRED","PROVISIONING","ACTIVE","SUSPENDED"]).parse(form.get("status"));await db.$transaction([db.subscription.update({where:{id},data:{provisioningStatus:status}}),db.auditLog.create({data:{actorId:session.user.id,action:"PROVISIONING_STATUS_CHANGED",targetType:"Subscription",targetId:id,metadata:{status}}})]);revalidatePath("/en/admin/subscriptions")}

export async function provisionSubscription(form:FormData){const session=await requireAdmin();const id=z.string().min(1).parse(form.get("subscriptionId"));await db.subscription.update({where:{id},data:{provisioningStatus:"PROVISIONING",provisioningError:null}});try{const result=await provisioningProvider.provision(id);await db.$transaction([db.subscription.update({where:{id},data:{externalTenantId:result.externalTenantId,externalAccessUrl:result.accessUrl,provisioningStatus:result.status,provisionedAt:new Date(),provisioningError:null}}),db.auditLog.create({data:{actorId:session.user.id,action:"PRODUCT_PROVISIONED",targetType:"Subscription",targetId:id,metadata:{externalTenantId:result.externalTenantId}}})])}catch(error){const message=error instanceof Error?error.message:"Provisioning failed";await db.$transaction([db.subscription.update({where:{id},data:{provisioningStatus:"SETUP_REQUIRED",provisioningError:message}}),db.auditLog.create({data:{actorId:session.user.id,action:"PRODUCT_PROVISIONING_FAILED",targetType:"Subscription",targetId:id,metadata:{error:message}}})])}revalidatePath("/en/admin/subscriptions");revalidatePath("/en/dashboard/products")}

export async function activateManualSubscription(form:FormData){const session=await requireAdmin();const id=z.string().min(1).parse(form.get("subscriptionId"));const subscription=await db.subscription.findUniqueOrThrow({where:{id}});if(subscription.provider!=="manual")throw new Error("Only manual plan requests can be activated here");await db.$transaction([db.subscription.update({where:{id},data:{status:"ACTIVE",provisioningStatus:"SETUP_REQUIRED",currentPeriodStart:new Date()}}),db.entitlement.upsert({where:{userId_productId_key:{userId:subscription.userId,productId:subscription.productId,key:"product_access"}},create:{userId:subscription.userId,productId:subscription.productId,subscriptionId:id,active:true},update:{subscriptionId:id,active:true,endsAt:null}}),db.auditLog.create({data:{actorId:session.user.id,action:"MANUAL_SUBSCRIPTION_ACTIVATED",targetType:"Subscription",targetId:id,metadata:{paymentTaken:false}}})]);revalidatePath("/en/admin/subscriptions");revalidatePath("/en/dashboard/products")}

const optionalUrl=z.union([z.literal(""),z.url()]).transform(value=>value||null);
const csv=(value:FormDataEntryValue|null)=>String(value||"").split("\n").map(x=>x.trim()).filter(Boolean);
const slug=z.string().trim().min(2).max(80).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
function refreshAdmin(){revalidatePath("/en/admin");revalidatePath("/en/admin/products");revalidatePath("/en/pricing");revalidatePath("/en/demos")}

export async function saveProduct(form:FormData){
 const session=await requireAdmin();
 const input=z.object({id:z.string().optional(),name:z.string().trim().min(2).max(100),slug,shortDescription:z.string().trim().min(5).max(240),description:z.string().trim().min(10).max(5000),icon:z.string().max(80).optional(),coverImage:optionalUrl,productionUrl:optionalUrl,status:z.enum(["DRAFT","ACTIVE","ARCHIVED"]),featured:z.enum(["on"]).optional(),displayOrder:z.coerce.number().int().min(0).max(10000)}).parse(Object.fromEntries(form));
 const data={name:input.name,slug:input.slug,shortDescription:input.shortDescription,description:input.description,icon:input.icon||null,coverImage:input.coverImage,productionUrl:input.productionUrl,status:input.status,featured:input.featured==="on",displayOrder:input.displayOrder,screenshots:csv(form.get("screenshots"))};
 const product=input.id?await db.product.update({where:{id:input.id},data}):await db.product.create({data});
 await db.auditLog.create({data:{actorId:session.user.id,action:input.id?"PRODUCT_UPDATED":"PRODUCT_CREATED",targetType:"Product",targetId:product.id,metadata:{slug:product.slug}}});refreshAdmin();
}

export async function savePlan(form:FormData){
 const session=await requireAdmin();
 const input=z.object({id:z.string().optional(),productId:z.string().min(1),name:z.string().trim().min(2).max(80),slug,monthlyPrice:z.coerce.number().nonnegative().max(100000000),annualPrice:z.coerce.number().nonnegative().max(100000000),currency:z.string().trim().length(3).transform(x=>x.toUpperCase()),trialDays:z.coerce.number().int().min(0).max(365),maxUsers:z.union([z.literal(""),z.coerce.number().int().positive()]).optional(),maxLocations:z.union([z.literal(""),z.coerce.number().int().positive()]).optional(),displayOrder:z.coerce.number().int().min(0),active:z.enum(["on"]).optional()}).parse(Object.fromEntries(form));
 const data={productId:input.productId,name:input.name,slug:input.slug,monthlyPrice:Math.round(input.monthlyPrice*100),annualPrice:Math.round(input.annualPrice*100),currency:input.currency,trialDays:input.trialDays,maxUsers:input.maxUsers===""||input.maxUsers===undefined?null:input.maxUsers,maxLocations:input.maxLocations===""||input.maxLocations===undefined?null:input.maxLocations,displayOrder:input.displayOrder,active:input.active==="on",features:csv(form.get("features")),limits:{}};
 const plan=input.id?await db.productPlan.update({where:{id:input.id},data}):await db.productPlan.create({data});
 await db.auditLog.create({data:{actorId:session.user.id,action:input.id?"PLAN_UPDATED":"PLAN_CREATED",targetType:"ProductPlan",targetId:plan.id,metadata:{productId:input.productId}}});refreshAdmin();
}

export async function saveDemo(form:FormData){
 const session=await requireAdmin();
 const input=z.object({id:z.string().optional(),productId:z.string().min(1),name:z.string().trim().min(2).max(100),url:z.url(),username:z.string().max(200).optional(),password:z.string().max(200).optional(),displayOrder:z.coerce.number().int().min(0),active:z.enum(["on"]).optional()}).parse(Object.fromEntries(form));
 const data={productId:input.productId,name:input.name,url:input.url,active:input.active==="on",displayOrder:input.displayOrder,credentials:input.username||input.password?{username:input.username||"",password:input.password||""}:undefined};
 const demo=input.id?await db.demoConfiguration.update({where:{id:input.id},data}):await db.demoConfiguration.create({data});
 await db.auditLog.create({data:{actorId:session.user.id,action:input.id?"DEMO_UPDATED":"DEMO_CREATED",targetType:"DemoConfiguration",targetId:demo.id,metadata:{productId:input.productId}}});refreshAdmin();
}

export async function updateClientStatus(form:FormData){const session=await requireAdmin();const id=z.string().min(1).parse(form.get("userId"));const status=z.enum(["ACTIVE","SUSPENDED","CLOSED"]).parse(form.get("status"));await db.$transaction([db.user.update({where:{id},data:{status}}),db.auditLog.create({data:{actorId:session.user.id,action:"CLIENT_STATUS_CHANGED",targetType:"User",targetId:id,metadata:{status}}})]);revalidatePath("/en/admin/clients")}

export async function updateMembership(form:FormData){const session=await requireAdmin();const id=z.string().min(1).parse(form.get("subscriptionId"));const status=z.enum(["TRIALING","ACTIVE","PAST_DUE","CANCELLED","EXPIRED","SUSPENDED"]).parse(form.get("status"));await db.subscription.update({where:{id},data:{status}});await db.$transaction([db.entitlement.updateMany({where:{subscriptionId:id},data:{active:status==="ACTIVE"||status==="TRIALING"}}),db.auditLog.create({data:{actorId:session.user.id,action:"MEMBERSHIP_STATUS_CHANGED",targetType:"Subscription",targetId:id,metadata:{status}}})]);revalidatePath("/en/admin/subscriptions");revalidatePath(`/en/dashboard/subscriptions`)}

export async function saveSiteSetting(form:FormData){const session=await requireAdmin();const key=slug.parse(form.get("key"));const locale=z.enum(["en","ar","he"]).parse(form.get("locale"));const raw=z.string().max(20000).parse(form.get("value"));let value:unknown=raw;try{value=JSON.parse(raw)}catch{}await db.$transaction([db.siteSetting.upsert({where:{key_locale:{key,locale}},create:{key,locale,value:value as never},update:{value:value as never}}),db.auditLog.create({data:{actorId:session.user.id,action:"SITE_CONTENT_UPDATED",targetType:"SiteSetting",targetId:`${key}:${locale}`,metadata:{key,locale}}})]);revalidatePath("/en/admin/content");revalidatePath(`/${locale}`)}
export async function updateRequest(form:FormData){const session=await requireAdmin();const id=z.string().min(1).parse(form.get("requestId"));const status=z.enum(["SUBMITTED","REVIEWING","APPROVED","IN_PROGRESS","COMPLETED","REJECTED"]).parse(form.get("status"));const internalNotes=z.string().max(5000).parse(form.get("internalNotes")||"");await db.$transaction([db.customizationRequest.update({where:{id},data:{status,internalNotes:internalNotes||null}}),db.auditLog.create({data:{actorId:session.user.id,action:"CUSTOMIZATION_REQUEST_UPDATED",targetType:"CustomizationRequest",targetId:id,metadata:{status}}})]);revalidatePath("/en/admin/requests")}
export async function updateTicket(form:FormData){const session=await requireAdmin();const id=z.string().min(1).parse(form.get("ticketId"));const status=z.enum(["OPEN","IN_PROGRESS","WAITING_FOR_CLIENT","RESOLVED","CLOSED"]).parse(form.get("status"));const reply=z.string().trim().max(5000).optional().parse(form.get("reply")||undefined);await db.$transaction([db.supportTicket.update({where:{id},data:{status,...(reply?{messages:{create:{authorId:session.user.id,body:reply}}}:{})}}),db.auditLog.create({data:{actorId:session.user.id,action:"SUPPORT_TICKET_UPDATED",targetType:"SupportTicket",targetId:id,metadata:{status,replied:Boolean(reply)}}})]);revalidatePath("/en/admin/support")}
