const crypto=require("crypto");
const express=require("express");
const router=express.Router();

function query(db,sql,args=[]){return new Promise((resolve,reject)=>db.query(sql,args,(error,result)=>error?reject(error):resolve(result)))}
function safeEqual(a,b){const left=Buffer.from(a||"", "hex"),right=Buffer.from(b||"", "hex");return left.length===right.length&&left.length>0&&crypto.timingSafeEqual(left,right)}
async function tables(db){await query(db,"CREATE TABLE IF NOT EXISTS platform_provisioning_events (event_id VARCHAR(191) PRIMARY KEY, tenant_id VARCHAR(64) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")}
router.post("/provision",async(req,res)=>{try{if(process.env.APP_MODE==="demo")return res.status(403).json({error:"Demo deployments cannot be provisioned"});const secret=process.env.PROVISIONING_SECRET||"";if(secret.length<32)return res.status(503).json({error:"Provisioning is not configured"});const timestamp=req.get("x-provisioning-timestamp")||"";if(Math.abs(Date.now()-Number(timestamp))>300000)return res.status(401).json({error:"Expired request"});const expected=crypto.createHmac("sha256",secret).update(`${timestamp}.${req.rawBody}`).digest("hex");if(!safeEqual(expected,req.get("x-provisioning-signature")))return res.status(401).json({error:"Invalid signature"});const body=req.body;if(body.productSlug!=="appointments"||!body.eventId||!body.subscriptionId||!body.customer?.email||!body.plan?.slug)return res.status(400).json({error:"Invalid payload"});await tables(req.db);const tenantId=`appointment-${crypto.createHash("sha256").update(body.subscriptionId).digest("hex").slice(0,20)}`;const prior=await query(req.db,"SELECT tenant_id FROM platform_provisioning_events WHERE event_id=?",[body.eventId]);if(!prior.length){const status=body.action==="suspend"?"SUSPENDED":"ACTIVE",name=body.business?.name||body.customer.name;await query(req.db,"INSERT INTO tenants (id,subscription_id,name,slug,plan_slug,plan_limits,status,default_language) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),plan_slug=VALUES(plan_slug),plan_limits=VALUES(plan_limits),status=VALUES(status),default_language=VALUES(default_language)",[tenantId,body.subscriptionId,name,tenantId,body.plan.slug,JSON.stringify(body.plan.limits||{}),status,["ar","en","he"].includes(body.customer.language)?body.customer.language:"en"]);await query(req.db,"INSERT INTO site_settings (tenant_id,id,shop_name) VALUES (?,1,?) ON DUPLICATE KEY UPDATE shop_name=VALUES(shop_name)",[tenantId,name]);await query(req.db,"INSERT INTO platform_provisioning_events (event_id,tenant_id) VALUES (?,?)",[body.eventId,tenantId])}const base=(process.env.PRODUCTION_APP_URL||"http://localhost:5173").replace(/\/$/,"");return res.json({externalTenantId:tenantId,accessUrl:`${base}/?tenant=${encodeURIComponent(tenantId)}`,status:"ACTIVE"})}catch(error){console.error("Provisioning error",error.message);return res.status(500).json({error:"Provisioning failed"})}});
module.exports=router;
