import {Prisma} from "@/generated/prisma/client";
import {db} from "@/lib/db";
import type {Actor} from "@/features/auth/authorization";
import {assertTransition} from "@/features/deliveries/state-machine";

export async function acceptFixedDelivery(actor:Actor,deliveryId:string){if(actor.role!=="COURIER")throw new Error("FORBIDDEN");return db.$transaction(async tx=>{const courier=await tx.courierProfile.findFirstOrThrow({where:{userId:actor.id,tenantId:actor.tenantId,availability:"AVAILABLE",suspendedAt:null}});const price=await offered(tx,deliveryId);const result=await tx.delivery.updateMany({where:{id:deliveryId,tenantId:actor.tenantId,status:"AVAILABLE",pricingMode:"FIXED",courierId:null},data:{status:"COURIER_SELECTED",courierId:courier.id,agreedPriceMinor:price}});if(result.count!==1)throw new Error("DELIVERY_UNAVAILABLE");const delivery=await tx.delivery.findUniqueOrThrow({where:{id:deliveryId},select:{id:true,offeredPriceMinor:true}});await tx.deliveryStatusHistory.create({data:{deliveryId,actorUserId:actor.id,previousStatus:"AVAILABLE",newStatus:"COURIER_SELECTED"}});await tx.conversation.create({data:{deliveryId}});await tx.deliveryOffer.updateMany({where:{deliveryId,status:"ACTIVE"},data:{status:"REJECTED"}});return delivery;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
async function offered(tx:Prisma.TransactionClient,id:string){return (await tx.delivery.findUniqueOrThrow({where:{id},select:{offeredPriceMinor:true}})).offeredPriceMinor;}

export async function selectOffer(actor:Actor,offerId:string){if(actor.role!=="BUSINESS")throw new Error("FORBIDDEN");return db.$transaction(async tx=>{const offer=await tx.deliveryOffer.findFirstOrThrow({where:{id:offerId,status:"ACTIVE",delivery:{tenantId:actor.tenantId,status:"AVAILABLE",business:{userId:actor.id}}},include:{delivery:true}});const claimed=await tx.delivery.updateMany({where:{id:offer.deliveryId,status:"AVAILABLE",courierId:null},data:{courierId:offer.courierId,status:"COURIER_SELECTED",agreedPriceMinor:offer.amountMinor}});if(claimed.count!==1)throw new Error("DELIVERY_UNAVAILABLE");await tx.deliveryOffer.updateMany({where:{deliveryId:offer.deliveryId,status:"ACTIVE"},data:{status:"REJECTED"}});await tx.deliveryOffer.update({where:{id:offer.id},data:{status:"SELECTED"}});await tx.deliveryStatusHistory.create({data:{deliveryId:offer.deliveryId,actorUserId:actor.id,previousStatus:"AVAILABLE",newStatus:"COURIER_SELECTED",metadata:{offerId}}});await tx.conversation.create({data:{deliveryId:offer.deliveryId}});return offer;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

export async function updateDeliveryStatus(actor:Actor,id:string,next:Parameters<typeof assertTransition>[1],reason?:string){return db.$transaction(async tx=>{const d=await tx.delivery.findFirstOrThrow({where:{id,tenantId:actor.tenantId},include:{business:{select:{userId:true}},courier:{select:{userId:true}}}});if(actor.role!=="ADMIN"&&d.business.userId!==actor.id&&d.courier?.userId!==actor.id)throw new Error("FORBIDDEN");assertTransition(d.status,next,actor.role);if(next.startsWith("CANCELLED")&&!reason)throw new Error("CANCELLATION_REASON_REQUIRED");const changed=await tx.delivery.updateMany({where:{id,status:d.status},data:{status:next,cancellationReason:reason,completedAt:next==="COMPLETED"?new Date():undefined}});if(changed.count!==1)throw new Error("CONCURRENT_UPDATE");await tx.deliveryStatusHistory.create({data:{deliveryId:id,actorUserId:actor.id,previousStatus:d.status,newStatus:next,metadata:reason?{reason}:undefined}});return tx.delivery.findUniqueOrThrow({where:{id}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
