import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Check } from "lucide-react";
import { productSeeds, demoUrl } from "@/config/products";
import { DemoLaunch, ProductVisual } from "@/components/site";
import { localeOf } from "@/lib/i18n";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=productSeeds.find(x=>x.slug===slug);return {title:p?.name||"Product",description:p?.description};}
export function generateStaticParams(){return productSeeds.map(p=>({slug:p.slug}))}
export default async function ProductPage({params}:{params:Promise<{locale:string,slug:string}>}){const {locale:raw,slug}=await params;const locale=localeOf(raw);const p=productSeeds.find(x=>x.slug===slug);if(!p)notFound();return <><section className="page-hero container"><div className="eyebrow">{p.eyebrow}</div><h1 className="display" style={{fontSize:'clamp(3rem,6vw,6rem)'}}>{p.name}</h1><p className="muted">{p.description}</p><div className="actions" style={{justifyContent:'center'}}><DemoLaunch url={demoUrl(p.slug)} name={p.name}/><Link className="button primary" href={`/${locale}/pricing?product=${p.slug}`}>View plans</Link></div></section><section className="section"><div className="container split"><ProductVisual kind={p.slug}/><div><div className="eyebrow">THE COMPLETE SYSTEM</div><h2 className="heading">Operate with confidence.</h2><p className="muted">A polished customer experience and practical management tools in one configurable platform.</p><div className="grid grid-3">{p.features.map(f=><div key={f} style={{display:'flex',gap:8}}><Check size={17} color={p.color}/>{f}</div>)}</div></div></div></section><section className="section"><div className="container"><div className="eyebrow">MADE FOR</div><h2 className="heading">Industries that fit.</h2><div className="capabilities" style={{justifyContent:'flex-start'}}>{p.industries.map(i=><span className="capability" key={i}>{i}</span>)}</div></div></section><section className="section"><div className="container card" style={{padding:45,textAlign:'center'}}><h2>Try it before you decide.</h2><p className="muted">Explore the demo, then choose the plan and customization level that suits your business.</p><div className="actions" style={{justifyContent:'center'}}><DemoLaunch url={demoUrl(p.slug)} name={p.name}/><Link className="button" href={`/${locale}/contact`}>Ask a question</Link></div></div></section></>}
