import "dotenv/config";import argon2 from "argon2";import {PrismaPg} from "@prisma/adapter-pg";import {PrismaClient} from "../generated/prisma/client";import {DEFAULT_BUSINESS_CATEGORIES} from "../features/categories/defaults";
if(process.env.NODE_ENV==="production")throw new Error("Seed is disabled in production");if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL required");const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
async function main(){
const password=await argon2.hash("Demo-only-password-123!",{type:argon2.argon2id});const tenant=await db.tenant.upsert({where:{slug:"default"},update:{},create:{name:"OpenDelivery Demo",slug:"default"}});const area=await db.serviceArea.upsert({where:{tenantId_name:{tenantId:tenant.id,name:"Nazareth Demo Area"}},update:{},create:{tenantId:tenant.id,name:"Nazareth Demo Area",city:"Nazareth",centerLat:32.6996,centerLng:35.3035}});
await Promise.all(DEFAULT_BUSINESS_CATEGORIES.map(name=>db.category.upsert({where:{tenantId_name:{tenantId:tenant.id,name}},update:{active:true},create:{tenantId:tenant.id,name}})));
async function user(email:string,name:string,phone:string,role:"BUSINESS"|"COURIER"|"ADMIN"){const u=await db.user.upsert({where:{email},update:{},create:{tenantId:tenant.id,email,emailVerified:true,name,phone,passwordHash:password,role,status:"ACTIVE",accounts:{create:{accountId:email,providerId:"credential",password}}}});return u}
const businessUser=await user("business@example.invalid","Pizza Roma Demo Owner","+972500000101","BUSINESS");await db.business.upsert({where:{userId:businessUser.id},update:{},create:{tenantId:tenant.id,userId:businessUser.id,name:"Pizza Roma Demo",category:"Restaurant",address:"1 Demo Street, Nazareth",latitude:32.6996,longitude:35.3035,city:"Nazareth",openingHours:{note:"Demo only"}}});
const courierUser=await user("courier@example.invalid","Ahmed Demo","+972500000102","COURIER");await db.courierProfile.upsert({where:{userId:courierUser.id},update:{},create:{tenantId:tenant.id,userId:courierUser.id,city:"Nazareth",vehicleType:"BICYCLE",serviceAreas:{create:{serviceAreaId:area.id}}}});await user("admin@example.invalid","Admin Demo","+972500000103","ADMIN");console.log("Development demo accounts created. Password: Demo-only-password-123!");
}
main().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>db.$disconnect());
