require("dotenv").config();
const mysql=require("mysql2/promise");const bcrypt=require("bcrypt");
const samples=[
 {id:"elite-barber",name:"Elite Barber",language:"en",owner:["Elite Owner","050-100-0000"],customers:[["Adam","050-111-0001"],["Sami","050-111-0002"],["Daniel","050-111-0003"]],dates:["2026-09-01","2026-09-08","2026-09-15"]},
 {id:"smile-clinic",name:"Smile Clinic",language:"ar",owner:["Smile Owner","050-200-0000"],customers:[["Lina","050-222-0001"],["Noor","050-222-0002"],["Maya","050-222-0003"]],dates:["2026-09-02","2026-09-09","2026-09-16"]},
 {id:"glow-beauty",name:"Glow Beauty",language:"he",owner:["Glow Owner","050-300-0000"],customers:[["Sara","050-333-0001"],["Amal","050-333-0002"],["Rania","050-333-0003"]],dates:["2026-09-03","2026-09-10","2026-09-17"]},
];
async function main(){if(process.env.NODE_ENV==="production")throw new Error("Sample tenant seed is disabled in production");const db=await mysql.createConnection({host:process.env.DB_HOST,user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME});const password=await bcrypt.hash("Demo123!",10);await db.beginTransaction();try{for(const tenant of samples){await db.query("INSERT INTO tenants(id,name,slug,status,plan_slug,plan_limits,default_language) VALUES(?,?,?,'ACTIVE','professional',JSON_OBJECT('maxUsers',10,'maxLocations',1),?) ON DUPLICATE KEY UPDATE name=VALUES(name),status='ACTIVE'",[tenant.id,tenant.name,tenant.id,tenant.language]);await db.query("INSERT INTO site_settings(tenant_id,id,shop_name) VALUES(?,1,?) ON DUPLICATE KEY UPDATE shop_name=VALUES(shop_name)",[tenant.id,tenant.name]);await db.query("INSERT INTO users(tenant_id,phonenumber,name,password,is_verified,role,is_active) VALUES(?,?,?,?,1,'admin',1) ON DUPLICATE KEY UPDATE name=VALUES(name),password=VALUES(password),is_verified=1,role='admin',is_active=1",[tenant.id,tenant.owner[1],tenant.owner[0],password]);for(const[name,phone]of tenant.customers)await db.query("INSERT INTO users(tenant_id,phonenumber,name,password,is_verified,role,is_active) VALUES(?,?,?,?,1,'normal',1) ON DUPLICATE KEY UPDATE name=VALUES(name),password=VALUES(password),is_verified=1,is_active=1",[tenant.id,phone,name,password]);for(let customerIndex=0;customerIndex<tenant.customers.length;customerIndex++){const[name,phone]=tenant.customers[customerIndex],time=`${String(9+customerIndex).padStart(2,"0")}:00:00`;for(const date of tenant.dates)await db.query("INSERT INTO appointments(tenant_id,name,phonenumber,a_date,a_time) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),phonenumber=VALUES(phonenumber)",[tenant.id,name,phone,date,time])}}await db.commit()}catch(error){await db.rollback();throw error}finally{await db.end()}console.log("Seeded 3 tenants, 9 customers, 3 owners, and 27 appointments. Password: Demo123!")}
main().catch(error=>{console.error(error);process.exit(1)});
