"use client";
import Link from "next/link";
import { ArrowRight, Code2, Gauge, Globe2, Layers3, ShieldCheck, Smartphone } from "lucide-react";
import { useState } from "react";
import { productSeeds } from "@/config/products";
import { dictionaries, type Locale } from "@/lib/i18n";
import { ProductVisual } from "./site";

export function Hero({locale}:{locale:Locale}){const t=dictionaries[locale].hero;return <section className="container hero"><div className="hero-copy"><div className="eyebrow">{t.eyebrow}</div><h1 className="display gradient-text">{t.title}</h1><p className="muted">{t.body}</p><div className="actions"><Link className="button primary" href={`/${locale}/#solutions`}>{t.solutions}<ArrowRight size={17}/></Link><Link className="button" href={`/${locale}/demos`}>{t.demos}</Link><Link className="button" href={`/${locale}/contact`}>{t.talk}</Link></div></div><div className="hero-visual" aria-label="Product interface previews"><div className="orbit"/><div className="ui-window"><div className="window-top"><i className="dot"/><i className="dot"/><i className="dot"/></div><div className="mini-grid"><div className="mini">09:00<br/>Booking</div><div className="mini">10:30<br/>Confirmed</div><div className="mini">12:00<br/>Available</div></div></div><div className="ui-window"><div className="window-top"><i className="dot"/><i className="dot"/><i className="dot"/></div><div className="mini-grid"><div className="mini tall">New arrivals<br/><br/>24 products</div><div className="mini tall">Cart<br/><br/>₪ 1,240</div><div className="mini tall">Orders<br/><br/>+18%</div></div></div><div className="ui-window"><div className="window-top"><i className="dot"/><i className="dot"/><i className="dot"/></div><div className="mini-grid"><div className="mini">Property map</div><div className="mini">Courier · 8 min</div><div className="mini">Live status</div></div></div></div></section>}

export function ProductGrid({locale}:{locale:Locale}){const dictionary=dictionaries[locale];const t=dictionary.common;return <div className="grid grid-4">{productSeeds.map(p=>{const localized=dictionary.products[p.slug as keyof typeof dictionary.products];return <article className="card product-card" style={{"--pc":p.color} as React.CSSProperties} key={p.slug}><div className="eyebrow">{p.eyebrow}</div><h3>{localized.name}</h3><p className="muted">{localized.description}</p><div className="features">{localized.features.map(f=><span className="chip" key={f}>{f}</span>)}</div><div className="actions"><Link className="button" href={`/${locale}/products/${p.slug}`}>{t.details}</Link><Link className="button accent" href={`/${locale}/pricing?product=${p.slug}`}>{t.subscribe}</Link></div></article>})}</div>}

export function Finder({locale}:{locale:Locale}){const [type,setType]=useState("");const map:Record<string,string>={service:"appointments",store:"ecommerce",property:"real-estate",delivery:"opendelivery"};const found=productSeeds.find(p=>p.slug===map[type]);return <div className="card" style={{padding:30}}><div className="eyebrow">SMART PRODUCT FINDER</div><h3 style={{fontSize:28}}>What does your business need?</h3><div className="grid grid-4">{[["service","Service business"],["store","Online store"],["property","Real estate"],["delivery","Delivery / logistics"]].map(([v,l])=><button key={v} className={`button ${type===v?'accent':''}`} onClick={()=>setType(v)}>{l}</button>)}</div>{found&&<div style={{marginTop:25,paddingTop:20,borderTop:'1px solid var(--line)'}}><span className="muted">Recommended</span><h3>{found.name}</h3><p className="muted">{found.description}</p><Link className="button primary" href={`/${locale}/products/${found.slug}`}>Explore solution <ArrowRight size={16}/></Link></div>}</div>}

export function HomeSections({locale}:{locale:Locale}){const capabilities=["Web Applications","Mobile Apps","SaaS Platforms","E-Commerce","Booking Systems","Automation","Admin Dashboards","Cloud Deployment"];const why=[[Layers3,"Ready-made foundations"],[Code2,"Fully customizable"],[Globe2,"Multi-language"],[Smartphone,"Mobile ready"],[Gauge,"Scalable"],[ShieldCheck,"Secure"]] as const;return <><section className="section"><div className="container"><div className="capabilities">{capabilities.map(x=><span className="capability" key={x}>{x}</span>)}</div></div></section><section className="section" id="solutions"><div className="container"><div className="eyebrow">READY-MADE SOLUTIONS</div><h2 className="heading">Built for real businesses.</h2><p className="muted" style={{maxWidth:650}}>Choose a complete digital platform, try it free, customize it to your brand, and launch faster.</p><ProductGrid locale={locale}/></div></section><section className="section"><div className="container"><Finder locale={locale}/></div></section><section className="section"><div className="container split"><div><div className="eyebrow">A BETTER STARTING POINT</div><h2 className="heading">Stop starting from zero.</h2><p className="muted">A ready-made foundation can reduce discovery and implementation work while preserving room for your brand and workflow.</p><Link className="button primary" href={`/${locale}/pricing`}>Compare plans</Link></div><div className="card compare">{[["Custom from zero","Long discovery and build"],["Our platform","Already working"],["Your launch","Branding + configuration"],["Growth","Subscription + support"]].map(([a,b])=><div className="compare-row" key={a}><strong>{a}</strong><span className="muted">{b}</span></div>)}</div></div></section><section className="section"><div className="container"><div className="grid grid-3">{why.map(([Icon,title])=><article className="card" style={{padding:25}} key={title}><Icon color="#a78bfa"/><h3>{title}</h3><p className="muted">Production-focused systems designed around usability, flexibility, and long-term growth.</p></article>)}</div></div></section><section className="section" id="custom"><div className="container card split" style={{padding:45}}><div><div className="eyebrow">CUSTOM DEVELOPMENT</div><h2 className="heading">Need something different?</h2><p className="muted">We build custom websites, mobile apps, SaaS systems, dashboards, APIs, automation, and internal tools.</p><Link className="button accent" href={`/${locale}/contact?type=custom`}>Build a custom application</Link></div><ProductVisual kind="custom"/></div></section></>}
